![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [45]:
# Import the system utilities and NumPy library.
# NumPy gives us arrays and math operations that are faster and more convenient than using plain Python lists.
import sys
import numpy as np

## Basic Numpy Arrays

In [46]:
# This creates a 1D NumPy array from a Python list.
# A NumPy array stores data more efficiently and supports math operations element by element.
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [47]:
# Store the array in a variable so we can reuse it later.
a = np.array([1, 2, 3, 4])

In [48]:
# This array contains floating-point numbers, so NumPy will infer a float dtype automatically.
b = np.array([0, .5, 1, 1.5, 2])

In [ ]:
# Indexing selects one or more positions from the array.
a[0], a[1]

(np.int64(1), np.int64(2))

In [ ]:
# Slicing from the start to the end keeps all remaining items.
a[0:]

array([1, 2, 3, 4])

In [ ]:
# This takes items from index 1 up to but not including index 3.
a[1:3]

array([2, 3])

In [ ]:
# Starting at index 1 and stopping before the last item.
a[1:-1]

array([2, 3])

In [ ]:
# The step of 2 means "take every second item".
a[::2]

array([1, 3])

In [ ]:
# This array has fractional values, so it is stored as floats.
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
# We can access specific positions with a few indexes.
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [ ]:
# A list of indexes allows us to select a custom subset of elements.
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [ ]:
# The array still contains integers, but NumPy records the data type separately.
a

array([1, 2, 3, 4])

In [ ]:
# dtype tells us the exact numeric type used in memory.
a.dtype

dtype('int64')

In [ ]:
# This is a float array because it contains decimals.
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
# dtype is float64 in this case, which is the default floating-point type for NumPy.
b.dtype

dtype('float64')

In [ ]:
# We can explicitly force a different data type when creating the array.
np.array([1, 2, 3, 4], dtype=float)

array([1., 2., 3., 4.])

In [ ]:
# Smaller integer types can save memory but hold fewer possible values.
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [ ]:
# Arrays do not have to be numeric; strings are also valid data.
c = np.array(['a', 'b', 'c'])

In [ ]:
# NumPy stores string arrays as a fixed-width text type.
c.dtype

dtype('<U1')

In [ ]:
# Mixed objects cannot be stored as a single numeric dtype, so NumPy falls back to object dtype.
d = np.array([{'a': 1}, sys])

In [ ]:
# object means each element is stored as a Python object, not a compact numeric type.
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [67]:
# A 2D array is like a matrix: rows and columns.
# The inner lists represent the rows, and each row has the same number of values.
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [68]:
# shape tells us the dimensions of the array: (rows, columns).
A.shape

(2, 3)

In [69]:
# ndim tells us how many dimensions the array has: 2 for a matrix, 1 for a vector.
A.ndim

2

In [70]:
# size is the total number of elements in the array.
A.size

6

In [ ]:
# This is a 3D array: it has layers, rows, and columns.
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [ ]:
# 3D arrays are useful for storing multiple 2D matrices together.
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
# shape shows the full layout as (layers, rows, columns).
B.shape

(2, 2, 3)

In [ ]:
# ndim reports the number of dimensions, so 3D arrays have ndim = 3.
B.ndim

3

In [ ]:
# size counts every value in the whole 3D structure.
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [76]:
# Inconsistent inner lengths prevent a single uniform numeric array, so NumPy creates an object array.
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
# This reveals that the array is no longer a strict multi-dimensional numeric array.
C.dtype

dtype('O')

In [ ]:
# shape is irregular because one nested list has a different length.
C.shape

(2,)

In [ ]:
# The total number of elements is still counted, but the structure is not homogeneous.
C.size

2

In [ ]:
# Each element inside the outer array is itself a Python list, not a uniform NumPy numeric block.
type(C[0])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [ ]:
# A square matrix is a 2D array where rows and columns have the same length.
# The comments show the index positions for rows and columns.
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [ ]:
# Access the second row of the matrix.
A[1]

array([4, 5, 6])

In [ ]:
# Access the first element in the second row.
A[1][0]

4

In [ ]:
# NumPy supports multi-dimensional indexing: A[row, column, ...].

In [ ]:
# This is the same as A[1][0], but written in a compact, 2D-index form.
A[1, 0]

4

In [ ]:
# Slicing rows: take the first two rows.
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# This keeps all rows and only the first two columns.
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
# Slice both dimensions to get the top-left 2x2 block.
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
# This selects the first two rows and the last column slice.
A[:2, 2:]

array([[3],
       [6]])

In [ ]:
# The original matrix is still there until we modify it.
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Replacing a whole row updates the row in place.
A[1] = np.array([10, 10, 10])

In [ ]:
# This shows the row assignment changed the second row.
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [ ]:
# Assigning a scalar to an entire row broadcasts the same value across all columns.
A[2] = 99

In [ ]:
# The third row is now filled with the value 99.
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [ ]:
# These summary methods reduce a vector to a single interpretable number.
a = np.array([1, 2, 3, 4])

In [ ]:
# sum() adds all values in the array.
a.sum()

10

In [ ]:
# mean() returns the average value.
a.mean()

2.5

In [ ]:
# std() measures standard deviation, showing how far values spread from the mean.
a.std()

1.118033988749895

In [ ]:
# var() gives the variance, which is the square of the standard deviation.
a.var()

1.25

In [ ]:
# Summary statistics are useful to understand the overall pattern of numeric data.
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# sum() adds all values together across the whole array.
A.sum()

45

In [ ]:
# mean() computes the average value for the full matrix.
A.mean()

5.0

In [ ]:
# std() measures how spread out the values are from the mean.
A.std()

2.581988897471611

In [ ]:
# axis=0 reduces each column into a single value, so we get a column-wise sum.
A.sum(axis=0) # column-wise sum

array([12, 15, 18])

In [ ]:
# axis=1 reduces each row into a single value, so we get a row-wise sum.
A.sum(axis=1) # row-wise sum

array([ 6, 15, 24])

In [ ]:
# This gives the average value in each column.
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
# This gives the average value in each row.
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
# Column-wise spread is computed with axis=0.
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
# Row-wise spread is computed with axis=1.
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [ ]:
# arange creates a sequence of numbers; here we create 0, 1, 2, 3.
a = np.arange(4)

In [ ]:
# This array has one value per position, like a vector.
a

array([0, 1, 2, 3])

In [ ]:
# Broadcasting allows us to add a scalar to every element in the array at once.
a + 10

array([10, 11, 12, 13])

In [ ]:
# Multiplication also applies to each element individually.
a * 10

array([ 0, 10, 20, 30])

In [ ]:
# The original array is unchanged unless we assign the result back.
a

array([0, 1, 2, 3])

In [ ]:
# In-place modification updates the existing array.
a += 100

In [ ]:
a

array([100, 101, 102, 103])

In [ ]:
# Compare this with a Python list comprehension; NumPy does it in a vectorized way.
l = [0, 1, 2, 3]

In [ ]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [ ]:
a = np.arange(4)

In [ ]:
# Vectorized operations can also happen between two arrays of the same shape.
a

array([0, 1, 2, 3])

In [ ]:
b = np.array([10, 10, 10, 10])

In [ ]:
# This array has one value for each position, so both arrays line up element by element.
b

array([10, 10, 10, 10])

In [ ]:
a + b

array([10, 11, 12, 13])

In [ ]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [ ]:
# Boolean masks let us filter data based on conditions instead of explicit indices.
a = np.arange(4)

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
# Integer indexing selects specific elements by position.
a[0], a[-1]

(0, 3)

In [ ]:
a[[0, -1]]

array([0, 3])

In [ ]:
# A boolean list is a mask: True means "keep this element".
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
# Compare each element against a threshold; this returns a boolean array.
a >= 2

array([False, False,  True,  True])

In [ ]:
# Using the condition as an index selects values greater than or equal to 2.
a[a >= 2]

array([2, 3])

In [ ]:
# The mean helps define a “middle” value for comparison.
a.mean()

1.5

In [ ]:
# Keep only the elements strictly above the average value.
a[a > a.mean()]

array([2, 3])

In [ ]:
# The tilde inverts the mask, so this selects values that are not above the mean.
a[~(a > a.mean())]

array([0, 1])

In [ ]:
# This uses OR to select values equal to 0 or 1.
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
# This uses AND with a modulo check to keep even numbers up to 2.
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [ ]:
# A 3x3 matrix of random integers is a common example for mask-based filtering.
A = np.random.randint(100, size=(3, 3))

In [ ]:
A


array([[74, 27, 51],
       [61, 58, 16],
       [57,  9, 31]])

In [ ]:
# This mask keeps only the cells where the pattern is True.
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([71, 42, 94,  2, 36])

In [ ]:
# A boolean matrix can be created by comparing every value to a threshold.
A > 30

array([[ True, False,  True],
       [ True,  True, False],
       [False,  True,  True]])

In [ ]:
# We can select only the values that satisfy the condition.
A[A > 30]

array([71, 42, 40, 94, 85, 36])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [ ]:
# Linear algebra in NumPy uses matrix operations, which are essential in data science and ML.
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
# B has 3 rows and 2 columns, so it can be multiplied by A using matrix multiplication.
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
# dot() computes the matrix product, combining rows from A with columns from B.
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
# @ is the same as dot() and is the standard Python operator for matrix multiplication.
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [ ]:
# T transposes the matrix, swapping rows and columns.
# The %time magic shows how quickly the operation runs.
%time B.T

CPU times: user 290 μs, sys: 74 μs, total: 364 μs
Wall time: 1.63 ms


array([[6, 4, 2],
       [5, 3, 1]])

In [ ]:
# This is the original matrix so we can compare it to its transpose.
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Multiplying the transpose by A is another matrix product with a different shape.
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [ ]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [ ]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [ ]:
# float is also stored compactly in NumPy compared with Python floats.
np.dtype(float).itemsize

8

### Lists are even larger

In [ ]:
# A one-element Python list still carries extra object overhead.
sys.getsizeof([1])

In [ ]:
# A NumPy array stores the raw numeric data with much less overhead.
np.array([1]).nbytes

### And performance is also important

In [ ]:
# This is a large Python list, which is slower to process in pure Python.
l = list(range(100000))

In [ ]:
# This is the equivalent NumPy array, optimized for fast vectorized math.
a = np.arange(100000)

In [ ]:
# NumPy performs the operation in compiled code, which is usually much faster.
%time np.sum(a ** 2)

CPU times: user 1.06 ms, sys: 279 µs, total: 1.34 ms
Wall time: 701 µs


333328333350000

In [ ]:
# Python list comprehension does the same logic one item at a time, which is slower.
%time sum([x ** 2 for x in l])

CPU times: user 36.1 ms, sys: 0 ns, total: 36.1 ms
Wall time: 35.5 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [ ]:
# random returns values uniformly between 0 and 1, which is useful for sampling.
np.random.random(size=2)

array([0.87191736, 0.29827741])

In [ ]:
# normal creates values using a bell-shaped (Gaussian) distribution.
np.random.normal(size=2)

array([0.46584391, 0.19162562])

In [ ]:
# rand can create a matrix of random numbers with a chosen shape.
np.random.rand(2, 4)

array([[0.05561617, 0.9971518 , 0.1215966 , 0.2214049 ],
       [0.25489594, 0.35425509, 0.96670996, 0.44098724]])

---
### `arange`

In [ ]:
# arange creates a sequence of numbers; this one is 0 through 9.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# This creates a range that starts at 5 and ends before 10.
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
# A step of 0.1 gives a floating-point series from 0 up to 1.
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [ ]:
# reshape changes the layout, not the order of the values.
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# The same 10 numbers can be reorganized into 5 rows and 2 columns.
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [ ]:
# linspace gives exact evenly spaced values over an interval.
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# More points gives a smoother sample of the same range.
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# False means do not include the final endpoint in the generated sequence.
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [ ]:
# zeros creates a vector full of zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# This creates a full 3x3 matrix of zeros.
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# dtype=int makes the values integer typed instead of float.
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# ones creates every value as 1, which is useful as a starting template.
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# This builds a 3x3 matrix of ones.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# empty allocates memory without initializing values, so it can contain garbage until filled.
np.empty(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# empty is faster than zeros if you will overwrite every value immediately.
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [ ]:
# identity creates a square matrix with 1s on the main diagonal.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# eye creates a matrix with ones along a diagonal and zeros elsewhere.
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# This rectangular matrix still keeps its diagonal pattern.
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# k=1 shifts the diagonal one column to the right.
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# k=-3 shifts the diagonal three columns to the left.
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
# String indexing works like list indexing: it returns the character at the requested position.
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)